parameters:
    stocarul_twitter.http.client.class: Stocarul\TwitterBundle\Http\Client
    stocarul_twitter.guzzle.oauth1.class: GuzzleHttp\Subscriber\Oauth\Oauth1

    stocarul_twitter.search.class: Stocarul\TwitterBundle\Service\Search

    stocarul_twitter.factory.tweet.class: Stocarul\TwitterBundle\Factory\TweetFactory

services:
    stocarul_twitter.oauth:
        class: %stocarul_twitter.guzzle.oauth1.class%
        arguments:
            - %stocarul_twitter.oauth%

    stocarul_twitter.client:
        class: %stocarul_twitter.http.client.class%
        arguments:
            - %stocarul_twitter.client%
        calls:
            - [addSubscriber, [@stocarul_twitter.oauth]]

    stocarul_twitter.search:
        class: %stocarul_twitter.search.class%
        arguments:
            - @stocarul_twitter.client
        calls:
            - [setTweetFactory, [@stocarul_twitter.factory.tweet]]

    stocarul_twitter.factory.tweet:
        class: %stocarul_twitter.factory.tweet.class%
