language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer update --prefer-source
  - cp Tests/Fixtures/App/config/parameters.yml.dist Tests/Fixtures/App/config/parameters.yml
